<!-- left menu starts -->
<div class="span2 main-menu-span">
	<div class="well nav-collapse sidebar-nav">
		<ul class="nav nav-tabs nav-stacked main-menu">
			<li class="nav-header hidden-tablet">主要功能</li>
            <li><a class="ajax-link" href="/youtube"><i class="icon-home"></i><span class="hidden-tablet"> YouTube</span></a></li>
			<li><a class="ajax-link" href="/index"><i class="icon-home"></i><span class="hidden-tablet"> 仪表盘</span></a></li>
			<li><a class="ajax-link" href="/ui"><i class="icon-eye-open"></i><span class="hidden-tablet"> UI界面</span></a></li>
			<li><a class="ajax-link" href="/form"><i class="icon-edit"></i><span class="hidden-tablet"> 表单</span></a></li>
			<li><a class="ajax-link" href="/chart"><i class="icon-list-alt"></i><span class="hidden-tablet"> 图标</span></a></li>
			<li><a class="ajax-link" href="/typography"><i class="icon-font"></i><span class="hidden-tablet"> 排版</span></a></li>
			<li><a class="ajax-link" href="/gallery"><i class="icon-picture"></i><span class="hidden-tablet"> 画廊</span></a></li>
			<li class="nav-header hidden-tablet">基本功能</li>
			<li><a class="ajax-link" href="/table"><i class="icon-align-justify"></i><span class="hidden-tablet"> 表格</span></a></li>
			<li><a class="ajax-link" href="/calendar"><i class="icon-calendar"></i><span class="hidden-tablet"> 日历</span></a></li>
			<li><a class="ajax-link" href="/grid"><i class="icon-th"></i><span class="hidden-tablet"> 网格</span></a></li>
			<li><a class="ajax-link" href="/file-manager"><i class="icon-folder-open"></i><span class="hidden-tablet"> 文件管理</span></a></li>
			<li><a href="/tour"><i class="icon-globe"></i><span class="hidden-tablet"> 游记</span></a></li>
			<li><a class="ajax-link" href="/icon"><i class="icon-star"></i><span class="hidden-tablet"> 图标</span></a></li>
			<li><a href="/error"><i class="icon-ban-circle"></i><span class="hidden-tablet"> 错误页面</span></a></li>
			<li><a href="/login"><i class="icon-lock"></i><span class="hidden-tablet"> 登录页面</span></a></li>
		</ul>
		<label id="for-is-ajax" class="hidden-tablet" for="is-ajax"><input id="is-ajax" type="checkbox"> Ajax on menu</label>
	</div><!--/.well -->
</div><!--/span-->
<!-- left menu ends -->